// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace VolunteerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolesPrivilegio", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("int")
                        .HasColumnName("PrivilegioID");

                    b.HasKey("RolId", "PrivilegioId")
                        .HasName("PK__RolesPri__41F8718A018018B3");

                    b.HasIndex("PrivilegioId");

                    b.ToTable("RolesPrivilegios", (string)null);
                });

            modelBuilder.Entity("VoluntariosEvento", b =>
                {
                    b.Property<int>("VoluntarioId")
                        .HasColumnType("int")
                        .HasColumnName("VoluntarioID");

                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("EventoID");

                    b.HasKey("VoluntarioId", "EventoId")
                        .HasName("PK__Voluntar__462C556F60FA8F90");

                    b.HasIndex("EventoId");

                    b.ToTable("VoluntariosEventos", (string)null);
                });

            modelBuilder.Entity("VolunteerApi.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dificultad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CursoId")
                        .HasName("PK__Cursos__7E023A376FD61217");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("VolunteerApi.Models.Donadore", b =>
                {
                    b.Property<int>("DonadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DonadorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonadorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CiNit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CI_NIT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroReferencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DonadorId")
                        .HasName("PK__Donadore__D79B10BE5A61778E");

                    b.HasIndex(new[] { "CiNit" }, "UQ__Donadore__2B8937240D6690EB")
                        .IsUnique();

                    b.ToTable("Donadores");
                });

            modelBuilder.Entity("VolunteerApi.Models.Especialidade", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EspecialidadID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EspecialidadId")
                        .HasName("PK__Especial__F907181181A41B8F");

                    b.HasIndex(new[] { "NombreEspecialidad" }, "UQ__Especial__448A2514E50ECBC4")
                        .IsUnique();

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("VolunteerApi.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrganizadorId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizadorID");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EventoId")
                        .HasName("PK__Eventos__1EEB590128839CF5");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("VolunteerApi.Models.HistorialCapacitacion", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistorialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int?>("VoluntarioId")
                        .HasColumnType("int")
                        .HasColumnName("VoluntarioID");

                    b.HasKey("HistorialId")
                        .HasName("PK__Historia__975206EFE6EA96FB");

                    b.HasIndex("CursoId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("HistorialCapacitacion", (string)null);
                });

            modelBuilder.Entity("VolunteerApi.Models.Privilegio", b =>
                {
                    b.Property<int>("PrivilegioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrivilegioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrivilegioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombrePrivilegio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PrivilegioId")
                        .HasName("PK__Privileg__8DB735BA409C3BE6");

                    b.HasIndex(new[] { "NombrePrivilegio" }, "UQ__Privileg__668E88A12F621B72")
                        .IsUnique();

                    b.ToTable("Privilegios");
                });

            modelBuilder.Entity("VolunteerApi.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__F92302D156830D92");

                    b.HasIndex(new[] { "NombreRol" }, "UQ__Roles__4F0B537F774CB6A2")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VolunteerApi.Models.SeguimientoSaludVoluntario", b =>
                {
                    b.Property<int>("SeguimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguimientoID"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionFisica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracionEjercicio")
                        .HasColumnType("int");

                    b.Property<string>("EnfermedadesCronicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAnimo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoVacunacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Estatura")
                        .HasColumnType("real");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<string>("FrecuenciaEjercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrecuenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<float?>("HorasSueño")
                        .HasColumnType("real");

                    b.Property<string>("Medicamentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEstres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("PresionArterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Temperatura")
                        .HasColumnType("real");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoluntarioID")
                        .HasColumnType("int");

                    b.HasKey("SeguimientoID");

                    b.ToTable("SeguimientoSaludVoluntarios");
                });

            modelBuilder.Entity("VolunteerApi.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int")
                        .HasColumnName("AdministradorID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("FechaLimite")
                        .HasColumnType("date");

                    b.Property<int?>("VoluntarioId")
                        .HasColumnType("int")
                        .HasColumnName("VoluntarioID");

                    b.HasKey("TareaId")
                        .HasName("PK__Tareas__5CD836712B58A928");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("VolunteerApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7983B948D4C");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534056DEFBD")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VolunteerApi.Models.Voluntario", b =>
                {
                    b.Property<int>("VoluntarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoluntarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoluntarioId"));

                    b.Property<string>("Domicilio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EspecialidadId")
                        .HasColumnType("int")
                        .HasColumnName("EspecialidadID");

                    b.Property<DateOnly?>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("NumeroCelular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("VoluntarioId")
                        .HasName("PK__Voluntar__47C2E0FFE85F1AC6");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ__Voluntar__2B3DE799B920D6A5")
                        .IsUnique()
                        .HasFilter("[UsuarioID] IS NOT NULL");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("RolesPrivilegio", b =>
                {
                    b.HasOne("VolunteerApi.Models.Privilegio", null)
                        .WithMany()
                        .HasForeignKey("PrivilegioId")
                        .IsRequired()
                        .HasConstraintName("FK__RolesPriv__Privi__3D5E1FD2");

                    b.HasOne("VolunteerApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__RolesPriv__RolID__3C69FB99");
                });

            modelBuilder.Entity("VoluntariosEvento", b =>
                {
                    b.HasOne("VolunteerApi.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired()
                        .HasConstraintName("FK__Voluntari__Event__6A30C649");

                    b.HasOne("VolunteerApi.Models.Voluntario", null)
                        .WithMany()
                        .HasForeignKey("VoluntarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Voluntari__Volun__693CA210");
                });

            modelBuilder.Entity("VolunteerApi.Models.Evento", b =>
                {
                    b.HasOne("VolunteerApi.Models.Usuario", "Organizador")
                        .WithMany("Eventos")
                        .HasForeignKey("OrganizadorId")
                        .HasConstraintName("FK__Eventos__Organiz__66603565");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("VolunteerApi.Models.HistorialCapacitacion", b =>
                {
                    b.HasOne("VolunteerApi.Models.Curso", "Curso")
                        .WithMany("HistorialCapacitacions")
                        .HasForeignKey("CursoId")
                        .HasConstraintName("FK__Historial__Curso__5DCAEF64");

                    b.HasOne("VolunteerApi.Models.Voluntario", "Voluntario")
                        .WithMany("HistorialCapacitacions")
                        .HasForeignKey("VoluntarioId")
                        .HasConstraintName("FK__Historial__Volun__5CD6CB2B");

                    b.Navigation("Curso");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("VolunteerApi.Models.Tarea", b =>
                {
                    b.HasOne("VolunteerApi.Models.Usuario", "Administrador")
                        .WithMany("Tareas")
                        .HasForeignKey("AdministradorId")
                        .HasConstraintName("FK__Tareas__Administ__6383C8BA");

                    b.HasOne("VolunteerApi.Models.Voluntario", "Voluntario")
                        .WithMany("Tareas")
                        .HasForeignKey("VoluntarioId")
                        .HasConstraintName("FK__Tareas__Voluntar__628FA481");

                    b.Navigation("Administrador");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("VolunteerApi.Models.Usuario", b =>
                {
                    b.HasOne("VolunteerApi.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__RolID__4222D4EF");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("VolunteerApi.Models.Voluntario", b =>
                {
                    b.HasOne("VolunteerApi.Models.Especialidade", "Especialidad")
                        .WithMany("Voluntarios")
                        .HasForeignKey("EspecialidadId")
                        .HasConstraintName("FK__Voluntari__Espec__571DF1D5");

                    b.HasOne("VolunteerApi.Models.Usuario", "Usuario")
                        .WithOne("Voluntario")
                        .HasForeignKey("VolunteerApi.Models.Voluntario", "UsuarioId")
                        .HasConstraintName("FK__Voluntari__Usuar__5629CD9C");

                    b.Navigation("Especialidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VolunteerApi.Models.Curso", b =>
                {
                    b.Navigation("HistorialCapacitacions");
                });

            modelBuilder.Entity("VolunteerApi.Models.Especialidade", b =>
                {
                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("VolunteerApi.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("VolunteerApi.Models.Usuario", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Tareas");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("VolunteerApi.Models.Voluntario", b =>
                {
                    b.Navigation("HistorialCapacitacions");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
